version: '3.7'

networks:
  backend:

services:
  nginx:
    image: nginx:1.19
    restart: unless-stopped
    ports:
      - ${APPLICATION_PORT}:80
    volumes:
      - ./deployment/nginx/dev.conf.d:/etc/nginx/conf.d
    networks:
      backend:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        BASE_IMAGE: node:12
        NODE_ENV: development
        BUILD_DIR: ${BUILD_DIR}
        NPM_AUTHTOKEN: ${NPM_AUTHTOKEN}
    command: npm run dev
    restart: unless-stopped
    volumes:
      - ./.env.development:${BUILD_DIR}/.env.development
      - ./components:${BUILD_DIR}/components
      - ./hooks:${BUILD_DIR}/hooks
      - ./interfaces:${BUILD_DIR}/interfaces
      - ./pages:${BUILD_DIR}/pages
      - ./public:${BUILD_DIR}/public
      - ./tests:${BUILD_DIR}/tests
      - ./util:${BUILD_DIR}/util
    networks:
      backend:
