module.exports = {
    publicRuntimeConfig: {
        NEXT_PUBLIC_DEPLOYMENT: process.env.NEXT_PUBLIC_DEPLOYMENT,

        NEXT_PUBLIC_UI_LIBRARY_HEADER_ECOCOMMONS_ROOT:
            process.env.NEXT_PUBLIC_UI_LIBRARY_HEADER_ECOCOMMONS_ROOT,
        NEXT_PUBLIC_UI_LIBRARY_HEADER_ECOCOMMONS_WORKSPACE:
            process.env.NEXT_PUBLIC_UI_LIBRARY_HEADER_ECOCOMMONS_WORKSPACE,
        NEXT_PUBLIC_UI_LIBRARY_HEADER_ECOCOMMONS_DATASETS:
            process.env.NEXT_PUBLIC_UI_LIBRARY_HEADER_ECOCOMMONS_DATASETS,
        NEXT_PUBLIC_UI_LIBRARY_HEADER_ECOCOMMONS_ANALYSIS_HUB:
            process.env.NEXT_PUBLIC_UI_LIBRARY_HEADER_ECOCOMMONS_ANALYSIS_HUB,

        NEXT_PUBLIC_KEYCLOAK_AUTH_URL:
            process.env.NEXT_PUBLIC_KEYCLOAK_AUTH_URL,
        NEXT_PUBLIC_KEYCLOAK_AUTH_REALM:
            process.env.NEXT_PUBLIC_KEYCLOAK_AUTH_REALM,
        NEXT_PUBLIC_KEYCLOAK_AUTH_CLIENT_ID:
            process.env.NEXT_PUBLIC_KEYCLOAK_AUTH_CLIENT_ID,

        NEXT_PUBLIC_ANALYSIS_PLAYGROUND_BACKEND_SERVER_URL:
            process.env.NEXT_PUBLIC_ANALYSIS_PLAYGROUND_BACKEND_SERVER_URL,
        NEXT_PUBLIC_ANALYSIS_TOOLS_MODELLING_WIZARDS_BCCVL_URL:
            process.env.NEXT_PUBLIC_ANALYSIS_TOOLS_MODELLING_WIZARDS_BCCVL_URL,

        NEXT_PUBLIC_JUPYTERHUB_SERVER_URL:
            process.env.NEXT_PUBLIC_JUPYTERHUB_SERVER_URL,

        NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID:
            process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID,
     
    },
};
